name: Check PR title

on:
  pull_request:
    types: [opened, edited]

jobs:
  parse-pr-body:
    name: Parse PR Body
    runs-on: ubuntu-latest
    steps:
      - name: Parse ENV_DATA
        run: |
          PR_BODY='${{ github.event.pull_request.body }}'
          ENV_DATA=$(echo "${PR_BODY}"| sed -nre 's/^.*ENV_DATA=(\S+).*$/\1/p')
          ENV_DATA=${ENV_DATA:-Dev}
          echo "ENV_DATA=${ENV_DATA}">>${GITHUB_ENV}
